services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-dev
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.cache/pypoetry:/root/.cache/pypoetry
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    env_file: .env
